#instalo node para que corra react
FROM node:16.16.0

#defino mi espacio de trabajo
WORKDIR /practica1front

#copio los package para q se instale bien
COPY package*.json ./

#instalo las dependencias a travez de los package.json
RUN npm install

#copio todo pero el dockerignore tambien hace de las suyas
COPY . .

#DOCKER COMPOUSE --------------------
EXPOSE 3000

#corro el front-end
CMD ["npm","start"]


