version: "3.8"

services:

  #database:
    #build:
    #  context: ./Mongodb
    #  dockerfile: Dockerfile
    #container_name: database #aqui el nombre puede ser cualquiera
    #restart: always           #cuando se vaya a mimir el contenedor se reiniciara xd
    #image: mysql:latest #aqui cambiamos xd
    #environment:
    #  MYSQL_ROOT_PASSWORD: '12345'
    #volumes:
    #  - ./db/data:/data/db   #lo de backup con docker volumen
      
    #ports:
    #  - "27017:27017"     #puertos
    

#----------------------------------------------------------------------------------

  backend:
    #build:
    #  context: ./backend/backend
    #  dockerfile: Dockerfile
    container_name: backend #puede ser cualquier nombre
    restart: always           #cuando se vaya a mimir el contenedor se reiniciara xd
    image: cesarchs17/backend_p1_201700634 #aqui cambiamos xd
    ports:
      - "8080:8080"
    #depends_on:
    #  - database
    #links:
    #  - database


  frontend:
    #build:
    #  context: ./frontend/practica1
    #  dockerfile: Dockerfile
    container_name: frontend #puede ser cualquier nombre
    restart: always           #cuando se vaya a mimir el contenedor se reiniciara xd
    image: cesarchs17/frontend_p1_201700634 #aqui cambiamos xd
    ports:
      - "3000:3000"
    depends_on:
      - backend
    links:
      - backend